### ISSUE TITLE
Unsupported filter pattern for graph traversal error thrown when using permissions profile. 

### ISSUE THREAD

**Issue by jdsantiagojr** [AEB-labs/cruddl#296]
Hello, 

I'm getting `Unsupported filter pattern for graph traversal ($Product_66.ctx.businessUnit IN literal [  "320859222"])` when I use the following permissions profile. 

```
entityName:
  permissions:
      - access:
          - create
          - read
          - update
        roles:
          - /^editor-bu-(.*)$/
        restrictions:
          - field: ctx.businessUnit
            valueTemplate: $1
```

The entities have a `ctx` child entity with `businessUnit` field. I'm hoping you can give me some information on why this might be occurring and how I might be able to resolve. 

Look forward to hearing back.
